"""empty message

Revision ID: 277d23d91995
Revises: fcc1c926016d
Create Date: 2020-09-19 10:23:58.871430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '277d23d91995'
down_revision = 'fcc1c926016d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Genres_of_Artists')
    op.drop_table('Genres_of_Venues')
    op.drop_table('Genre')
    op.add_column('Artist', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('Venue', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'genres')
    op.drop_column('Artist', 'genres')
    op.create_table('Genres_of_Venues',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genres_of_Venues_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('venue_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='Genres_of_Venues_genre_id_fkey'),
    sa.ForeignKeyConstraint(['venue_id'], ['Venue.id'], name='Genres_of_Venues_venue_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Genres_of_Venues_pkey')
    )
    op.create_table('Genres_of_Artists',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genres_of_Artists_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('artist_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('genre_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['Artist.id'], name='Genres_of_Artists_artist_id_fkey'),
    sa.ForeignKeyConstraint(['genre_id'], ['Genre.id'], name='Genres_of_Artists_genre_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='Genres_of_Artists_pkey')
    )
    op.create_table('Genre',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Genre_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='Genre_pkey')
    )
    # ### end Alembic commands ###
