"""empty message

Revision ID: 7bf1d246e955
Revises: 6375964492bb
Create Date: 2020-09-17 12:27:21.430811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf1d246e955'
down_revision = '6375964492bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Show', sa.Column('date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Show', 'date')
    # ### end Alembic commands ###
